BEGIN
table_load_image('LOAD_DIR','1','googlelogo.png','googlelogo.png');
table_load_image('LOAD_DIR','2','netar.png','netar.png');
table_load_image('LOAD_DIR','3','mastercard.png','mastercard.png');
table_load_image('LOAD_DIR','4','blackyak.jpg','blackyak.jpg');
table_load_image('LOAD_DIR','5','vans.png','vans.png');
table_load_image('LOAD_DIR','6','logos.jpg','logos.jpg');
table_load_image('LOAD_DIR','7','tmax.png','tmax.png');
table_load_image('LOAD_DIR','8','user-guide.pdf','user-guide.pdf');
table_load_image('LOAD_DIR','9','T-UP_Migrator.mp4','T-UP_Migrator.mp4');
END;
/
