drop table TEST_1 cascade constraints;
drop table TEST_3 cascade constraints;
drop TABLESPACE TSTEST_3_1  including contents and datafiles;
drop TABLESPACE TSTEST_3_2  including contents and datafiles;
drop table TEST_5 cascade constraints;
drop TABLESPACE TSTEST_5_1  including contents and datafiles;
drop TABLESPACE TSTEST_5_2  including contents and datafiles;
drop table TEST_7 cascade constraints;
drop TABLESPACE TSTEST_7_1  including contents and datafiles;
drop TABLESPACE TSTEST_7_2  including contents and datafiles;
drop table TEST_10 cascade constraints;
drop table TEST_12 cascade constraints;
drop table TEST_14 cascade constraints;
drop table TEST_16 cascade constraints;
drop table TEST_18 cascade constraints;
drop table TEST_20 cascade constraints;
drop TABLESPACE TSTEST_20_1 including contents and datafiles;
drop TABLESPACE TSTEST_20_2 including contents and datafiles;
drop table TEST_21 cascade constraints;
drop TABLESPACE TSTEST_21_1 including contents and datafiles;
drop TABLESPACE TSTEST_21_2 including contents and datafiles;
drop table TEST_22 cascade constraints;
drop table TEST_23 cascade constraints;
drop table TEST_24 cascade constraints;
drop table TEST_25 cascade constraints;
drop table TEST_27 cascade constraints;
drop table TEST_28 cascade constraints;
drop table TEST_29 cascade constraints;
drop table TEST_30 cascade constraints;
drop table TEST_31_2 cascade constraints;
drop table TEST_31_1 cascade constraints;
drop table TEST_32 cascade constraints;
drop table TEST_33 cascade constraints;
drop table TEST_36_1 cascade constraints;
drop table TEST_36_2 cascade constraints;
drop table T_DATA_TYPE_CHAR;
drop table T_DATA_TYPE_VARCHAR;
drop table T_DATA_TYPE_DATE;
drop table T_DATA_TYPE_TIMESTAMP;
drop table T_DATA_TYPE_COMPOSIT1;
drop table T_CHARACTER;
